require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  AllowedMethods: ["describe"]

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
